import type { CharacterData, Player } from "@/lib/types";
import type { BackgroundData } from "@/lib/data/backgrounds";
import type { ClassData } from "@/lib/data/classes";
import type { RaceData } from "@/lib/data/races";
import type { ArchetypeCasting } from "@/lib/data/classAbilities";
import type { MutableRefObject } from "react";

export type SheetCtx = {
  form: Player | null;
  formRef: MutableRefObject<Player | null>;
  cd: CharacterData;
  attacks: any[];
  spellSlots: Record<number, { total?: number; expended?: number }>;
  conditions: string[];
  clsKey: string | null;
  clsData: ClassData | null;
  raceData: RaceData | null;
  bgData: BackgroundData | null;
  archCasting: ArchetypeCasting | null;
  level: number;
  pb: number;
  hitDie: number | undefined;
  conMod: number;
  dexMod: number;
  raceSpeed: number | undefined;
  expectedHP: number | null;
  spellAbility: string | undefined;
  spellAbilityScore: number;
  spellAbilityMod: number;
  spellDC: number;
  spellAtk: number;
  autoSlotTotals: Record<number, number>;
  cantripLimit: number;
  preparedLimit: number;
  spellLimit: number;
  totalKnown: number;
  classSkillSet: Set<string>;
  bgSkillSet: Set<string>;
  raceSkillSet: Set<string>;
  upd: (key: string, value: any) => void;
  updCd: (key: string, value: any) => void;
  updCdAll: (obj: Record<string, any>) => void;
  updAll: (obj: Record<string, any>) => void;
  save: (fields: Record<string, any>) => void;
  onLevelUp: (updates: Record<string, any>) => void;
  onAddAttack: (attack: { name: string; bonus: string; damage: string; type: string }) => void;
};